# Generated by Django 4.1.2 on 2024-06-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCate', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='idProd', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=350)),
                ('descripcion', models.CharField(max_length=400)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='media')),
                ('fk_categoria', models.ForeignKey(db_column='idCate', on_delete=django.db.models.deletion.CASCADE, to='coffe.categoria')),
            ],
        ),
    ]
