# Generated by Django 4.1.2 on 2024-06-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
